### ISSUE TITLE
Google sign-in not working

### ISSUE THREAD

**Issue by ali-waris** [CodelightStudios/Android-Smart-Login#14] opened 2016-03-20 11:26 UTC
I am able to include the library successfully in my project, but Google sign-in is not working.
It stucks at "Getting user info" and remains there. 

Facebook login is working perfectly.

Please help me with Google sign-in or suggest me where am I going wrong.

**Comment by vipinagrahari** [comment] 2016-03-22 14:54
Facing the same problem.

**Comment by ali-waris** [comment] 2016-03-22 15:49
Hey,  try signing your app using signingConfig in gradle file. I am not using this library anymore. Using google's native sdk code, but there also i was facing same signing issues. Then, I signed my app using default debug key (from gradle), and voila...!!!  Everything works like a charm now. Hope it helps you too.

**Comment by kalyandechiraju** [comment] 2016-03-22 19:16
Hi @ali-waris. Did u try using signingConfig with this library ? It seems like the issue is with signing configuration not with the library.

**Comment by ali-waris** [comment] 2016-03-23 03:29
Yes,  maybe. Actually I found the solution when I implemented authentication for Google and Facebook by scratch (following Native documentation). I would recommend everyone to just check their signingConfig if Google login doesn't work. 

This solves my issue. Hence, closing it.

**Comment by kalyandechiraju** [comment] 2016-04-05 17:31
Hi @ali-waris Can you share the signInConfig code that you used in build file?

**Comment by kalyandechiraju** [comment] 2016-04-05 17:49
I have changed the Google sign-in API, as the v1 is deprecated. Even with the new sign-in API, login is being failed. 

RCA: 
```java
GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
```
This `result.isSuccess()` is being `false` always. Seems like some config problem. Requesting help here.

**Comment by kalyandechiraju** [comment] 2016-04-24 15:20
@ali-waris Can you share the signInConfig code that you used in build file?

**Comment by rohansood42** [comment] 2016-04-27 23:50
04-28 05:11:58.308 28860-28860/rohansood.yolo.com.loginproject I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.

This is happening on my device. My UI gets stuck when i try logging in.

**Comment by kalyandechiraju** [comment] 2016-04-28 01:52
@rohansood42 This is because of some google config issue, login didn't happen and a progress dialog is leaked and causing this issue. Please get the current version of the project and try. I have updated to v2 of Google login API. I will make sure that the next version is available on jcenter soon.

**Comment by rohansood42** [comment] 2016-04-28 11:01
Can i get the updated aar and test it out? @kalyandechiraju

**Comment by agenco12** [comment] 2016-10-11 21:41
hi @kalyandechiraju you were able to run the login with google? can you tell me how can I do? to me always returns the error "google login failed".

**Comment by kalyandechiraju** [comment] 2017-04-23 09:14
@ali-waris @vipinagrahari @rohansood42 @agenco12 The issue is resolved in new version 1.x. Check out README for more details. Project Wiki will be ready soon.

**Closed by kalyandechiraju** 2017-04-23 09:14 UTC
Labels: help wanted, Waiting for response
